Sd 4598 enable workflow processing for oldvalue and ischanged
amuratech/sd-workflow pull request #108
Opened 2021-02-22 06:47 UTC by cosmicmeditator

2021-02-24 06:15 UTC, abhishek-bhuskute requested changes
Needs some fixes. Also, check if this breaks existing functionality.

2021-02-24 06:15 UTC, abhishek-bhuskute commented on src/main/java/com/kylas/sales/workflow/domain/processor/WorkflowProcessor.java
> +        : conditionFacade.satisfies(expression, event.getOldEntity());
Will we ever reach the last return statement?

2021-02-24 06:15 UTC, abhishek-bhuskute commented on src/main/java/com/kylas/sales/workflow/domain/processor/WorkflowProcessor.java
> +    return !newPropertyName.equals(oldPropertyName);
Does this handle nested null value? What happens if you try to fetch property `salutation.id` and `salutation` itself is null?
Extract a method out of the handled code fragment.

2021-02-24 06:15 UTC, abhishek-bhuskute commented on src/test/resources/contracts/mq/events/lead-created-triggering-conditional-workflows-old-value-multiple-conditions.json
> +}
Shouldn't we refer to the same file if their content is exactly same-
- lead-created-triggering-conditional-workflows--multiple-conditions.json
- lead-created-triggering-conditional-workflows-ischanged-multiple-conditions.json
- lead-created-triggering-conditional-workflows-old-value-multiple-conditions.json

2021-02-24 11:44 UTC, abhishek-bhuskute commented on src/test/resources/contracts/mq/events/lead-created-triggering-conditional-workflows-old-value-multiple-conditions.json
> +}
This hasn't been addressed yet.

2021-02-24 11:45 UTC, abhishek-bhuskute requested changes
I still see 3 new identical JSON files.

2021-02-24 12:09 UTC, abhishek-bhuskute approved these changes

2021-02-26 07:52 UTC, bhaskarpawar123 approved these changes

2021-02-26 08:46 UTC, merged