Sd 4834 publish send email event from wf
amuratech/sd-workflow pull request #127
Opened 2021-03-16 11:21 UTC by bhaskarpawar123

2021-03-18 05:46 UTC, alpeshjikadra requested changes
Needs to fix integration test data

2021-03-18 10:05 UTC, alpeshjikadra requested changes

2021-03-18 10:05 UTC, alpeshjikadra commented on src/test/resources/test-scripts/integration/insert-workflow-for-email-action-test-record-primary-email.sql
> +('a0eebc55-9c0b-4ef8-bb6d-6bb9bd380a17','RECORD_OWNER', 'user', 12, 'user1', 'user1@gmail.com');
Why there is value for entityId and email for this entity_type ?

2021-03-19 02:17 UTC, bhaskarpawar123 commented on src/it/java/com/kylas/sales/workflow/EmailActionIntegrationTests.java
> +  private final String authenticationToken =
resolved. I am using it now..

2021-03-19 02:19 UTC, bhaskarpawar123 commented on src/it/java/com/kylas/sales/workflow/EmailActionIntegrationTests.java
> +    given(authService.getLoggedInUser()).willReturn(aUser);
i have removed mocks from the class

2021-03-19 02:20 UTC, bhaskarpawar123 commented on src/test/resources/test-scripts/integration/insert-workflow-for-email-action-test-record-primary-email.sql
> +('a0eebc55-9c0b-4ef8-bb6d-6bb9bd380a17','RECORD_OWNER', 'user', 12, 'user1', 'user1@gmail.com');
changed in all the places wherever it is required.

2021-03-19 02:22 UTC, bhaskarpawar123 commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +  public void updateEntityDetailInEmailRecipient(EmailType emailType, EntityEvent entityEvent) {
We need this method to update the lead/contact information, when lead/contact updated if it is available in any of to, cc, or bcc

2021-03-22 05:18 UTC, alpeshjikadra approved these changes

2021-03-22 05:22 UTC, alpeshjikadra approved these changes

2021-03-22 05:39 UTC, merged