SD-3739: Include pipeline IdName while fetching workflow if applicable
amuratech/sd-workflow pull request #47
Opened 2020-12-28 07:48 UTC by abhishek-bhuskute

- Resolve pipeline-name while fetching an edit-property action

2020-12-29 12:13 UTC, alpeshjikadra requested changes

2020-12-29 12:13 UTC, alpeshjikadra commented on src/test/resources/contracts/workflow/api/integration/workflow-301-update-with-pipeline-edit.json
> +      },
This must not be metadata anymore

2020-12-29 12:13 UTC, alpeshjikadra commented on src/test/resources/contracts/workflow/api/integration/workflow-301-update-with-pipeline-edit.json
> +        "value": "1",
And this must be an object IdName

2020-12-29 12:13 UTC, alpeshjikadra commented on src/test/resources/contracts/workflow/api/update-workflow-pipeline-request.json
> +        "value": 1,
This also be an IdName right ?

2020-12-29 12:23 UTC, abhishek-bhuskute commented on src/test/resources/contracts/workflow/api/integration/workflow-301-update-with-pipeline-edit.json
> +      },
This file is not being used anymore. I had added a new one. Removed this.

2020-12-29 12:23 UTC, abhishek-bhuskute commented on src/test/resources/contracts/workflow/api/integration/workflow-301-update-with-pipeline-edit.json
> +        "value": "1",
Same goes for this.

2020-12-29 12:24 UTC, abhishek-bhuskute commented on src/test/resources/contracts/workflow/api/update-workflow-pipeline-request.json
> +        "value": 1,
Right. This one is not being used. Deleted these.

2020-12-30 06:22 UTC, bhaskarpawar123 approved these changes

2020-12-30 07:01 UTC, alpeshjikadra approved these changes

2020-12-30 07:12 UTC, merged