fixed updating workflow action type.
amuratech/sd-workflow pull request #61
Opened 2021-01-06 10:58 UTC by bhaskarpawar123

2021-01-06 12:45 UTC, alpeshjikadra requested changes

2021-01-06 12:45 UTC, alpeshjikadra commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +                        existingAction -> existingAction.getId().equals(requestedAction.getId()) && existingAction.getType()
There must be some test cases to fix this

2021-01-07 03:52 UTC, bhaskarpawar123 commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +                        existingAction -> existingAction.getId().equals(requestedAction.getId()) && existingAction.getType()
have added test cases

2021-01-07 04:25 UTC, alpeshjikadra approved these changes

2021-01-07 05:02 UTC, abhishek-bhuskute approved these changes

2021-01-07 05:03 UTC, merged