Support id name for remaining fields
amuratech/sd-workflow pull request #68
Opened 2021-01-12 04:26 UTC by akshaykylas94

2021-01-12 10:36 UTC, alpeshjikadra requested changes

2021-01-12 10:36 UTC, alpeshjikadra commented on src/main/java/com/kylas/sales/workflow/domain/service/ValueResolver.java
> +  }
Which test cases cover this method execution ?

2021-01-14 04:25 UTC, abhishek-bhuskute approved these changes

2021-01-14 05:06 UTC, alpeshjikadra approved these changes

2021-01-14 05:07 UTC, merged