create and update workflow for deal
amuratech/sd-workflow pull request #70
Opened 2021-01-15 07:25 UTC by bhaskarpawar123

2021-01-18 10:29 UTC, abhishek-bhuskute commented on src/main/java/com/kylas/sales/workflow/domain/workflow/EntityType.java
> +  LEAD, USER, TENANT, CUSTOM, CONTACT, DEAL
Workflow can be created on all entities listed here. Please add a `boolean workflowEntity` property here and keep it true for LEAD & DEAL to use isWorkflowEntity() on them while validating workflow request.

2021-01-18 10:36 UTC, abhishek-bhuskute requested changes
Let's try to keep high order functions readable.

2021-01-18 10:36 UTC, abhishek-bhuskute commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +                      })
Try to move this code to the request validator. Otherwise, extract action under `map()` as a method, so that this remains readable.

2021-01-18 10:36 UTC, abhishek-bhuskute commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +                                  request.getActions(), workflow.getWorkflowActions(), request.getEntityType());
Does this one read better- `updateOrCreateActions(request, workflow)`
That way, you can check specifics inside the lower-order function.

2021-01-18 12:04 UTC, bhaskarpawar123 commented on src/main/java/com/kylas/sales/workflow/domain/workflow/EntityType.java
> +  LEAD, USER, TENANT, CUSTOM, CONTACT, DEAL
made changes

2021-01-18 12:04 UTC, bhaskarpawar123 commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +                      })
made changes

2021-01-18 12:04 UTC, bhaskarpawar123 commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +                                  request.getActions(), workflow.getWorkflowActions(), request.getEntityType());
made changes

2021-01-18 12:22 UTC, abhishek-bhuskute requested changes

2021-01-18 12:22 UTC, abhishek-bhuskute commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +
Can we move validating actions in `validate()`. This is a part of the request validation.

2021-01-19 06:11 UTC, abhishek-bhuskute commented on src/main/java/com/kylas/sales/workflow/api/WorkflowService.java
> +    workflowFacade.validate(workflowRequest);
Good stuff!

2021-01-19 06:12 UTC, abhishek-bhuskute commented on src/main/java/com/kylas/sales/workflow/domain/WorkflowFacade.java
> +
I liked it :+1:

2021-01-19 06:12 UTC, abhishek-bhuskute approved these changes

2021-01-19 06:14 UTC, merged