support create and update task on workflow
amuratech/sd-workflow pull request #96
Opened 2021-02-09 05:05 UTC by bhaskarpawar123

2021-02-09 12:07 UTC, alpeshjikadra requested changes

2021-02-09 12:07 UTC, alpeshjikadra commented on src/main/resources/db/migration/R__create_create_task_action_table.sql
> +  due_date VARCHAR(255) NOT NULL,
this should be dueDate which can be EmbeddedClass

2021-02-09 12:10 UTC, alpeshjikadra commented on src/main/resources/db/migration/R__create_create_task_action_table.sql
> +  due_date VARCHAR(255) NOT NULL,
Check **estimatedValue** In Deal.java into sd-deal service

2021-02-09 12:15 UTC, bhaskarpawar123 commented on src/it/java/com/kylas/sales/workflow/ContactWorkflowIntegrationTests.java
> +  public void givenContactWorkflowRequest_withCreateTaskAction_shouldUpdateIt() throws IOException {
should i remove entityname from the testname?

2021-02-09 12:31 UTC, alpeshjikadra commented on src/it/java/com/kylas/sales/workflow/ContactWorkflowIntegrationTests.java
> +  public void givenContactWorkflowRequest_withCreateTaskAction_shouldUpdateIt() throws IOException {
givenContactWorkflowUpdateRequest_withNewTaskAction_shouldUpdateWorkflow()

2021-02-09 12:33 UTC, alpeshjikadra commented on src/main/resources/db/migration/R__create_create_task_action_table.sql
> +  due_date VARCHAR(255) NOT NULL,
keep 2 separate column and use Embadable object
1. due_days
2. due_hours

2021-02-10 03:49 UTC, alpeshjikadra submitted a review, later dismissed

2021-02-10 04:04 UTC, alpeshjikadra approved these changes

2021-02-10 04:04 UTC, merged